config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :todos
  patch "todos/complete/:id", to: "todos#complete", as: "todo_complete"
  get "saipratap99/myusers", to: "todos#myusers"
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  validates :todo_text, presence: true, length: { minimum: 5 }
  validates :due_date, presence: true

  def to_pleasant_string
    status = completed ? "[X]" : "[ ]"
    "#{id}. #{due_date.to_s(:short)} #{todo_text} #{status}"
  end

  def self.overdue
    where("due_date < ?", Date.parse(Date.today.to_s))
    #return Todo object array for due_date is less than Date.today"
  end

  def self.due_today
    where("due_date = ?", Date.parse(Date.today.to_s))
  end

  def self.due_later
    where("due_date > ?", Date.parse(Date.today.to_s))
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!

  skip_before_action :verify_authenticity_token

  def index
  end

  def show
    redirect_to edit_todo_path
  end

  def create
    new_todo = Todo.create!(todo_params)
    redirect_to todos_path
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def edit
  end

  def complete
    todo = Todo.find(params[:id])
    todo.completed = todo.completed.!
    todo.save
    redirect_to todos_path
  end

  def destroy
    Todo.find(params[:id]).destroy
    redirect_to todos_path
  end

  def myusers
    if current_user.email == "pratap.sai99@gmail.com"
      render plain: User.all.map { |user| "#{user.email} NAME:#{user.name}  || #{user.todos.to_a} " }.join("\n")
    else
      render plain: "Not Allowed"
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:todo_text, :due_date).merge(completed: false, user_id: current_user.id)
  end

  def update_todo
    params.require(:todo).permit(:todo_text, :due_date, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<main class="main-body">
  <img src="welcome-center.png" class="img-welcomeCenter" style="display:block,margin:0 auto">
  <h2 class="home-h2">Organise Your <br>
    todos now<br>
    <%=link_to "Get started",todos_path,class:"get-started"%>
  </h2>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="Header">
      <h2> Todo Management</h2>
      <p>
        <%if user_signed_in?%>
          <span class="header-greetings">Hello <strong><%= current_user.name %></strong></span>
          <span calss="header-editProfile"><%=link_to "Edit Profile",edit_user_registration_path%></span>
          <span calss="header-logOut"><%=link_to "Log Out",destroy_user_session_path,method: :delete%></span>
        <% else %>
          <span class="header-signIn"> <%=link_to "Sign In",new_user_session_path%></span>
          <span class="header-signUp" > <%=link_to "Sign Up",new_user_registration_path%></span>
        <%end%>
      </p>
      <div class="dropdown">
        <%if user_signed_in?%>
          <span class="name-icon"><%= current_user.name[0] %></span>
          <div class="user-content">
            <p>
              <%=link_to "Edit Profile",edit_user_registration_path%>
            </p>
            <p>
              <%=link_to "Log Out",destroy_user_session_path,method: :delete%>
            </p>
          </div>
        <% else %>
          <span class="name-icon">N</span>
          <div class="user-content">
            <p> <%=link_to "Sign In",new_user_session_path%></p>
            <p> <%=link_to "Sign Up",new_user_registration_path%></p>
          </div>
        <%end%>
      </div>
    </div>
    <%if notice%>
      <p class="notice"><%= notice %></p>
    <%end%>
    <%if alert%>
      <p class="alert"><%= alert %></p>
    <%end%>
    <%= yield %>
    <footer class="Footer"> &copy; All copyrights are reserved. @Sai Pratap</footer>
  </body>
</html>

app/views/todos/_todosection-todo.html.erb
<ul class="TodoSection">
  <h2 class="TodoSection-title"><%= todo_heading %><span class="TodoSection-status"><%=todos.where(completed:true).count %>/<%=todos.count %></span></h2>
  <% todos.each do |todo| %>
    <li class="TodoSection-todo" >
      <label class="todos-lable" for=<%= todo.id %> >
        <%= form_with( url: "todos/#{todo.id}" , method: "PUT" ) do%>
          <input class="TodoSection-todoCheckbox"
                 name="completed"
                 onclick = this.form.submit()
                 id=<%= todo.id %>
                 type="checkbox"
                 <%= todo.completed ? "checked" : "" %>
          >
        <% end %>
        <span <% if todo.completed %>
              style="text-decoration:line-through"
               <% end %>
        >
          <%= todo.todo_text.capitalize %>
        </span>
        <% if show_date %>
          <span class="TodoSection-dueDate">
            <%= todo.due_date.to_s(:short) %>
          </span>
        <% end %>
      </label>
      <%= link_to todo, method: :delete, data: {confirm: 'Are you sure?'} do %>
        <%= image_tag "trash.png", class: "TodoSection-todoDelete" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/todos/edit.html.erb
<main class=todoUpdate-body>
  <h1 class="updateTodo-title">Update Todo</h1>
  <%= form_with scope: :todo,method: :patch,url: todo_path,class:"updateTodo-form",local: true do |form| %>
    <%= form.text_field :todo_text , placeholder: "Edit todo here",class:"updateTodo-text",value: Todo.find(params[:id]).todo_text %>
    <%= form.date_field :due_date , placeholder: "DD-MM-YYYY" ,class:"updateTodo-date",value:Todo.find(params[:id]).due_date %>
    <%= form.submit "Update",class:"updateTodo-button" %>
  <% end %>
  <%= form_with scope: :todo,method: :patch,url: todo_complete_path, local: true do |form| %>
    <% if Todo.find(params[:id]).completed %>
      <%= form.submit "Mark as Incomplete",class:"updateTodo-completeButton"%>
    <% else %>
      <%= form.submit "Mark as complete",class:"updateTodo-completeButton"%>
    <%end%>
  <%end%>
</main>

app/views/todos/index.html.erb
<article class="todosPage-body">
  <h1 class="Todo-title">My Todo-List</h1>
  <%= form_with scope: :todo,class:"todoAdd-form", local: true do |form| %>
    <%= form.text_field :todo_text , placeholder: "What's next?" %>
    <%= form.date_field :due_date , placeholder: "DD-MM-YYYY" %>
    <%= form.submit "Add",id:"todos_addForm" %>
  <% end %>
</form>
<%= render partial: "todosection-todo",locals: {todo_heading: "Overdue" , todos: current_user.todos.overdue ,show_date: true } %>
<%= render partial: "todosection-todo",locals: {todo_heading: "Due Today", todos: current_user.todos.due_today ,show_date: false } %>
<%= render partial: "todosection-todo",locals: {todo_heading: "Due Later", todos: current_user.todos.due_later ,show_date: true } %>
</article>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2 style="font-weight=bold">
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>